### PR TITLE
Recursive data serialization

### PR DESCRIPTION
**Pull request by asmfreak**
Fixed README.md. Implemented recursive serialization. All tests are green.

### CODE REVIEW

**Comment by msiemens** [comment]
Just to make sure I understand it right: The bug you fix is that serialization currently doesn't apply to nested fields, right?

**Comment by asmfreak** [comment]
Yes. I was working on a small project using TinyDB, when I stumbled on the need to put `datetime` objects into DB. So I googled this repo. And it happened so that my datetime objects resided in a dict inside a list, inside a dict inside a list inside a dict.

**Comment by msiemens** [comment]
Thanks for reporting and submitting a PR!

**Comment by msiemens** [comment]
I've done some refactoring and have now published v1.0.3 with the fix :)

**Pull request merged**
